### ISSUE TITLE
Toasts dark theme?

### ISSUE THREAD

**Issue by argyleink** [RiskChallenger/open-components#4]
Everything else has a great dark mode, but the toasts seem to be stuck on light

**Comment by argyleink** [comment]
also, i see the stacking todo, and i can help!

if you're down with JS, I made one you can take the code
- [demo](https://gui-challenges.web.app/toast/dist/)
- [src](https://github.com/argyleink/gui-challenges/tree/main/toast)

but! you might be able to get away with using `:has()` and quantity queries on children 🙂

**Comment by rienheuver** [comment]
I believe toasts do switch theme? It's just that they use a contrasting background. So dark toasts in light them and vice versa. I think that just gives a bit more attention to them. I'm afraid that they wouldn't get noticed enough otherwise. Though perhaps a light toast in dark mode could be annoying if you're checking your phone late at night in the dark huh? :sweat_smile: For now I accepted that trade off though, but suggestions are most welcome! Perhaps a small `--brand` border?

Love the toast stack demo by the way! And would love something like that, but then indeed css only. I want to keep installation and usage as simple as possible (and as framework agnostic as possible). That's also why I left interaction with the tabs for example up to the user. Any solution with `:has()` would be super neat though! We'll have to put a Firefox-disclaimer in the docs in that case ;-)

**Comment by argyleink** [comment]
>  I think that just gives a bit more attention to them
cool, good enough of an answer for me 🙂

**Comment by rienheuver** [comment]
Cool, I'll close it then :) anyone feel free to re-open it if you have new arguments to change this
